#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

$app = new Minicli\App();

$app->setSignature("minicli hello name [ user=name ]");

$app->registerCommand("help", function(Minicli\CommandCall $call) use ($app) {
    $app->printSignature();
    print_r($call->params);
});

$app->runCommand($argv);