#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

$app = new Minicli\App();

$app->registerController('hello', new \App\Commands\HelloController($app));

$app->registerCommand('help', function () use($app) {
    $app->getPrinter()->display("Minicli USAGE: help list ...");
});

$app->runCommand($argv);