#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';

$app = new Minicli\App();

$app->registerCommand('hello', function (array $argv) use($app) {
    $name = $argv[2] ?? 'World';
    $app->getPrinter()->display("Hello {$name}\n");
});

$app->registerCommand('help', function () use($app) {
    $app->getPrinter()->display("Minicli USAGE: help list ...");
});

$app->runCommand($argv);